### ISSUE TITLE
[suggestion] Is there any possibility to change TASKBAR ACTIVE/HOVER COLOR?

### ISSUE THREAD

**Issue by daidaiworm** [Raymai97/AccentPaletteTool#2]
winxp and win7 are both customizable.

https://filestore.community.support.microsoft.com/api/images/fb9cb3f0-6415-4edc-a8f5-2c4d1d99acb0

Not sure whether you can see the pic. Below is the link

# Active window taskbar icon color stand out windows 10 - Microsoft Community
https://answers.microsoft.com/en-us/windows/forum/all/active-window-taskbar-icon-color-stand-out-windows/5521f184-c332-4ca3-ba41-1d3d9f2991f9

**Comment by Raymai97** [comment]
Hi @daidaiworm 

Sorry, I don't think it is possible to do this.
